// GENERATED by scripts/build-legal-registry.mjs - do not edit by hand.
// Per-app legal content, produced from each app's surge.manifest.yaml by
// Daedalus/tools/legal_gen. The [slug] routes render these via the shared
// LegalShell; the master policy lists them as covered products.
import ladle from "./ladle.json";

export type LegalSection = { heading: string; body: string[] };
export type LegalDoc = {
  title: string;
  eyebrow: string;
  intro: string;
  sections: LegalSection[];
};
export type AppLegal = {
  slug: string;
  appName: string;
  privacy: LegalDoc;
  terms: LegalDoc;
};

const registry: Record<string, AppLegal> = {
  ladle: ladle as AppLegal,
};

export function getAppLegal(slug: string): AppLegal | undefined {
  return registry[slug];
}

export function legalSlugs(): string[] {
  return Object.keys(registry);
}

// Every app under the Surge Studios LLC umbrella, for the master policy's
// "products we cover" list.
export function coveredApps(): { slug: string; name: string }[] {
  return Object.values(registry)
    .map((a) => ({ slug: a.slug, name: a.appName }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
